[ONOS-8141] Fix for duplicate candidate node id for device mastership
atomix/atomix pull request #1098
Opened 2021-07-07 08:50 UTC by AnuragChadha

We have seen below exception in ONOS cluster:

ERROR | onos-device-manager-background | DeviceManager                    | 190 - org.onosproject.onos-core-net - 2.3.0 | Exception thrown during integrity check
java.lang.IllegalArgumentException: Multiple entries with same key: s17mn1vmsdc03=STANDBY and s17mn1vmsdc03=STANDBY
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[?:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:357) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.buildMastershipFromLeadership(ConsistentDeviceMastershipStore.java:321) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getMastership(ConsistentDeviceMastershipStore.java:198) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishLocalRole(ConsistentDeviceMastershipStore.java:295) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishRole(ConsistentDeviceMastershipStore.java:272) ~[?:?]
	at org.onosproject.cluster.impl.MastershipManager.relinquishMastership(MastershipManager.java:212) ~[?:?]
	at org.onosproject.net.device.impl.DeviceManager.mastershipCheck(DeviceManager.java:471) ~[?:?]
	at org.onosproject.net.device.impl.DeviceManager.lambda$activate$0(DeviceManager.java:217) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

And after this exception some devices are not able to connect to any onos node.
We tried changing mastership of those devices using device-role command in ONOS CLI and we observed below exception:

DeviceManager                    | 190 - org.onosproject.onos-core-net - 2.3.0 | Failed to handle MastershipEvent{time=2021-06-29T18:51:42.684Z, type=MASTER_CHANGED, subject=netconf:fdfd:fd60:1600:400::5b3:830, mastershipInfo=MastershipInfo{term=255, master=Optional[s17mn1vmsdc01], roles={s17mn1vmsdc01=MASTER, s17mn1vmsdc03=STANDBY, s17mn1vmsdc02=STANDBY}}}
java.lang.IllegalArgumentException: Multiple entries with same key: s17mn1vmsdc02=STANDBY and s17mn1vmsdc02=STANDBY
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[?:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:357) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.buildMastershipFromLeadership(ConsistentDeviceMastershipStore.java:321) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getMastership(ConsistentDeviceMastershipStore.java:198) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishLocalRole(ConsistentDeviceMastershipStore.java:295) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishRole(ConsistentDeviceMastershipStore.java:272) ~[?:?]
	at org.onosproject.cluster.impl.MastershipManager.relinquishMastership(MastershipManager.java:212) ~[?:?]
	at org.onosproject.net.device.impl.DeviceManager.handleMastershipEvent(DeviceManager.java:982) ~[?:?]
	at org.onosproject.net.device.impl.DeviceManager$InternalMastershipListener.lambda$event$0(DeviceManager.java:1002) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

One observation so far is that we have seen some StorageException and only after that we see the above exception of integrity checks.

Storage exception on ONOS1:

2021-06-29T18:50:59,834 | ERROR | onos-netconfDeviceProviderConnection-connection-executor-5 | NetconfDeviceProvider            | 216 - org.onosproject.onos-providers-netconf-device - 2.3.0 | Unhandled Exception
org.onosproject.store.service.StorageException: org.onosproject.store.service.StorageException: An application error occurred
	at org.onosproject.store.primitives.DefaultLeaderElector.complete(DefaultLeaderElector.java:117) ~[?:?]
	at org.onosproject.store.primitives.DefaultLeaderElector.withdraw(DefaultLeaderElector.java:55) ~[?:?]
	at org.onosproject.store.cluster.impl.DistributedLeadershipStore.removeRegistration(DistributedLeadershipStore.java:230) ~[?:?]
	at org.onosproject.cluster.impl.LeadershipManager.withdraw(LeadershipManager.java:97) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishLocalRole(ConsistentDeviceMastershipStore.java:294) ~[?:?]
	at org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishRole(ConsistentDeviceMastershipStore.java:272) ~[?:?]
	at org.onosproject.cluster.impl.MastershipManager.relinquishMastership(MastershipManager.java:212) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.initiateConnection(NetconfDeviceProvider.java:532) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.lambda$roleChanged$1(NetconfDeviceProvider.java:300) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.lambda$withDeviceLock$12(NetconfDeviceProvider.java:679) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.withDeviceLock(NetconfDeviceProvider.java:670) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.lambda$withDeviceLock$13(NetconfDeviceProvider.java:678) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.lambda$roleChanged$2(NetconfDeviceProvider.java:300) ~[?:?]
	at org.onosproject.provider.netconf.device.impl.NetconfDeviceProvider.lambda$exceptionSafe$5(NetconfDeviceProvider.java:434) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.onosproject.store.service.StorageException: An application error occurred
	at org.onosproject.store.atomix.primitives.impl.AtomixFutures.lambda$adaptFuture$0(AtomixFutures.java:54) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at io.atomix.utils.concurrent.AtomixFuture.lambda$wrap$0(AtomixFuture.java:48) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
 [...]

2021-07-07 17:19 UTC, pierventre requested changes
I believe we should do this in other places in this file. I found the same problem also in DefaultLeaderElectionService

2021-07-07 17:33 UTC, AnuragChadha commented
In DefaultLeaderElectionService at all places byte array comparison is used except in cleanup method for session. I believe cleanup session should be done on the basis of session id only so I could do the same in DefaultLeaderElectorService also. Let me know of this is fine @pierventre

2021-07-07 17:33 UTC, pierventre approved these changes
NVM was a different id. Should we write a small unit test ?

2021-07-08 03:04 UTC, AnuragChadha commented
DefaultLeaderElectorService does not have any UT as of now. Do you want me to write UT for the entire class ? @pierventre

2021-07-08 03:14 UTC, AnuragChadha commented
Also the if check in addRegistration method which is checking if session id of registration matches with already added registration might not be required now as duplicate check takes care of that by ensuring that onos node id cannot be registered again so session id of different onos node id will always be different. Please confirm @kuujo

2021-07-08 06:52 UTC, pierventre commented
> DefaultLeaderElectorService does not have any UT as of now. Do you want me to write UT for the entire class ? @pierventre

No, I was thinking just for this particular scenario see if DefaultLeaderElectionServiceTest can help you to write the test

2021-07-08 07:56 UTC, AnuragChadha commented
@pierventre Sure will add UT for testing duplicate candidate node.

2021-07-16 10:27 UTC, pierventre approved these changes

2021-08-10 18:35 UTC, kuujo approved these changes

2021-08-10 18:35 UTC, merged